import turtle
import random
screen = turtle.Screen()
screen.screensize(500,500)
screen.bgcolor('black')
t = turtle.Turtle()
t2=turtle.Turtle()
t3=turtle.Turtle()
t2.hideturtle()
t3.hideturtle()
FORCE_FACTOR = 30

#intro screen

t.penup()
t.goto(0,200)
t.pendown()
screen.addshape("a.gif")
t.shape("a.gif")
t.stamp()
t.shape("classic")
t.penup()
t.goto(0,200)
t.pendown()

t.penup()
t.goto(0,320)
t.pendown()
screen.addshape("5.gif")
t.shape("5.gif")
t.stamp()
t.shape("classic")
t.penup()
t.goto(0,320)
t.pendown()

t2.penup()
t2.pendown()
#circle
t.penup()
t.goto(0, -200)
t.pendown()
t.pencolor('green')
t.fillcolor('green')
t.begin_fill()
t.circle(75)
t.end_fill()
t2.pencolor("white")
t2.write('My name is Antonovich Perry and this is my project', font=("ariel", 20, "italic"), align="center")
round = input("Press Enter to Continue: ")

t.clear()
t2.clear()

#second screen

t.penup()
t.goto(0,200)
t.pendown()
screen.addshape("6.gif")
t.shape("6.gif")
t.stamp()
t.shape("classic")
t.penup()
t.goto(0,200)
t.pendown()

t.penup()
t.goto(0,320)
t.pendown()
screen.addshape("7.gif")
t.shape("7.gif")
t.stamp()
t.shape("classic")
t.penup()
t.goto(0,320)
t.pendown()

t.penup()
t.goto(0, -200)
t.pendown()
t.pencolor('white')
t.fillcolor('white')
t.begin_fill()
t.forward(180)
t.left(90)
t.forward(180)
t.left(90)
t.forward(180)
t.left(90)
t.end_fill()


t2.penup()
t2.pendown()
screen.bgcolor('black')
t2.write('My favorite food is ribs and chicken', font=("ariel", 20, "italic"), align="center")
round = input("Press Enter to Continue: ")

t.clear()
t2.clear()


#third screen

t.speed(0)
t.penup()
t.goto(0, -200)
t.pendown()
t.setheading(135)
t.fillcolor("brown")
t.begin_fill()
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.end_fill()


t.penup()
t.goto(0,200)
t.pendown()
screen.addshape("8.gif")
t.shape("8.gif")
t.stamp()
t.shape("classic")
t.penup()
t.goto(0,200)
t.pendown()

t.penup()
t.goto(0,320)
t.pendown()
screen.addshape("9.gif")
t.shape("9.gif")
t.stamp()
t.shape("classic")
t.penup()
t.goto(0,320)
t.pendown()


screen.bgcolor('black')
t2.pendown()
t2.write('My favorite hobbies are playing the game and sleeping ', font=("ariel", 20, "italic"), align="center")
round = input("Press Enter to Continue: ")

t.clear()
t2.clear()
#fourth screen

t.penup()
t.goto(0,200)
t.pendown()
screen.addshape("8.gif")
t.shape("8.gif")
t.stamp()
t.shape("classic")
t.penup()
t.goto(0,200)
t.pendown()

t.penup()
t.goto(0,320)
t.pendown()
screen.addshape("9.gif")
t.shape("9.gif")
t.stamp()
t.shape("classic")
t.penup()
t.goto(0,320)
t.pendown()

t.clear()
t2.clear()


screen.bgcolor('black')
t2.pendown()
t2.write('Favorite Movie is Karate Kid 2', font=("ariel", 30, "italic"), align="center")
round = input("Press Enter to Continue: ")

t.penup()
t.goto(0,200)
t.pendown()
screen.addshape("10.gif")
t.shape("10.gif")
t.stamp()
t.shape("classic")
t.penup()
t.goto(0,200)
t.pendown()

t.penup()
t.goto(0,320)
t.pendown()
screen.addshape("11.gif")
t.shape("11.gif")
t.stamp()
t.shape("classic")
t.penup()
t.goto(0,320)
t.pendown()

t.clear()
t2.clear()


#fifth screen
screen.bgcolor('black')
t2.pendown()
t2.write('My favorite Sport soccer', font=("ariel", 30, "italic"), align="center")
round = input("Press Enter to Continue: ")

t.penup()
t.goto(0,200)
t.pendown()
screen.addshape("12.gif")
t.shape("12.gif")
t.stamp()
t.shape("classic")
t.penup()
t.goto(0,200)
t.pendown()

t.penup()
t.goto(0,320)
t.pendown()
screen.addshape("13.gif")
t.shape("13.gif")
t.stamp()
t.shape("classic")
t.penup()
t.goto(0,320)
t.pendown()


turtle.done()